version: '3.7'

networks:
  ${COMPOSE_PROJECT_NAME}:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge

services:
  ws.${ORG1_PEER0_ID}:
    container_name: ws.${ORG1_PEER0_ID}
    image: couchdb:${COUCHDB_VERSION}
    environment:
      - COUCHDB_USER=${ORG1_PEER0_COUCHDB_USER}
      - COUCHDB_PASSWORD=${ORG1_PEER0_COUCHDB_PASSWORD}
    ports:
      - \"${ORG1_PEER0_COUCHDB_PORT_EXTERNAL}:${ORG1_PEER0_COUCHDB_PORT_INTERNAL}\"
    networks:
      - ${COMPOSE_PROJECT_NAME}

  ${ORG1_PEER0_ID}:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=ws.${ORG1_PEER0_ID}:${ORG1_PEER0_COUCHDB_PORT_INTERNAL}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${ORG1_PEER0_COUCHDB_USER}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${ORG1_PEER0_COUCHDB_PASSWORD}
    depends_on:
      - ws.${ORG1_PEER0_ID}

  ws.${ORG2_PEER0_ID}:
    container_name: ws.${ORG2_PEER0_ID}
    image: couchdb:${COUCHDB_VERSION}
    environment:
      - COUCHDB_USER=${ORG2_PEER0_COUCHDB_USER}
      - COUCHDB_PASSWORD=${ORG2_PEER0_COUCHDB_PASSWORD}
    ports:
      - \"${ORG2_PEER0_COUCHDB_PORT_EXTERNAL}:${ORG2_PEER0_COUCHDB_PORT_INTERNAL}\"
    networks:
      - ${COMPOSE_PROJECT_NAME}

  ${ORG2_PEER0_ID}:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=ws.${ORG2_PEER0_ID}:${ORG2_PEER0_COUCHDB_PORT_INTERNAL}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${ORG2_PEER0_COUCHDB_USER}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${ORG2_PEER0_COUCHDB_PASSWORD}
    depends_on:
      - ws.${ORG2_PEER0_ID}
