version: '3.7'

volumes:
  ${ORDERING_SERVICE_NODE_ID}:
  ${ORG1_PEER0_ID}:
  ${ORG2_PEER0_ID}:

networks:
  ${COMPOSE_PROJECT_NAME}:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge

services:

  ${ORDERING_SERVICE_NODE_ID}:
    container_name: ${ORDERING_SERVICE_NODE_ID}
    image: hyperledger/fabric-orderer:${HLF_VERSION}
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=${ORDERING_SERVICE_GRPC_PORT_INTERNAL}
      - ORDERER_GENERAL_LOCALMSPID=${ORDERING_ORG_MSP_ID}
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:${ORDERING_SERVICE_REST_PORT_INTERNAL}
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ${CRYPTO_PATH_HOST}/ordererOrganizations/${ORDERING_ORG_DOMAIN}/orderers/${ORDERING_SERVICE_NODE_ID}/msp:/var/hyperledger/orderer/msp
        - ${CRYPTO_PATH_HOST}/ordererOrganizations/${ORDERING_ORG_DOMAIN}/orderers/${ORDERING_SERVICE_NODE_ID}/tls:/var/hyperledger/orderer/tls
    ports:
      - \"${ORDERING_SERVICE_GRPC_PORT_EXTERNAL}:${ORDERING_SERVICE_GRPC_PORT_INTERNAL}\"
      - \"${ORDERING_SERVICE_REST_PORT_EXTERNAL}:${ORDERING_SERVICE_REST_PORT_INTERNAL}\"
    networks:
      - ${COMPOSE_PROJECT_NAME}

  ${ORG1_PEER0_ID}:
    container_name: ${ORG1_PEER0_ID}
    image: hyperledger/fabric-peer:${HLF_VERSION}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_ID=${ORG1_PEER0_ID}
      - CORE_PEER_LOCALMSPID=${ORG1_MSP_ID}
      - CORE_PEER_ADDRESS=${ORG1_PEER0_ID}:${ORG1_PEER0_PORT_INTERNAL}
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${ORG1_PEER0_PORT_INTERNAL}
      - CORE_PEER_CHAINCODEADDRESS=${ORG1_PEER0_ID}:${ORG1_PEER0_CHAINCODE_PORT}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${ORG1_PEER0_CHAINCODE_PORT}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_GOSSIP_BOOTSTRAP=${ORG1_PEER0_ID}:${ORG1_PEER0_PORT_INTERNAL}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${ORG1_PEER0_ID}:${ORG1_PEER0_PORT_INTERNAL}
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ${CRYPTO_PATH_HOST}/peerOrganizations/${ORG1_DOMAIN}/peers/${ORG1_PEER0_ID}/msp:/etc/hyperledger/fabric/msp
        - ${CRYPTO_PATH_HOST}/peerOrganizations/${ORG1_DOMAIN}/peers/${ORG1_PEER0_ID}/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - \"${ORG1_PEER0_PORT_EXTERNAL}:${ORG1_PEER0_PORT_INTERNAL}\"
    networks:
      - ${COMPOSE_PROJECT_NAME}

  ${ORG2_PEER0_ID}:
    container_name: ${ORG2_PEER0_ID}
    image: hyperledger/fabric-peer:${HLF_VERSION}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_ID=${ORG2_PEER0_ID}
      - CORE_PEER_LOCALMSPID=${ORG2_MSP_ID}
      - CORE_PEER_ADDRESS=${ORG2_PEER0_ID}:${ORG2_PEER0_PORT_INTERNAL}
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${ORG2_PEER0_PORT_INTERNAL}
      - CORE_PEER_CHAINCODEADDRESS=${ORG2_PEER0_ID}:${ORG2_PEER0_CHAINCODE_PORT}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${ORG2_PEER0_CHAINCODE_PORT}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_GOSSIP_BOOTSTRAP=${ORG2_PEER0_ID}:${ORG2_PEER0_PORT_INTERNAL}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${ORG2_PEER0_ID}:${ORG2_PEER0_PORT_INTERNAL}
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ${CRYPTO_PATH_HOST}/peerOrganizations/${ORG2_DOMAIN}/peers/${ORG2_PEER0_ID}/msp:/etc/hyperledger/fabric/msp
      - ${CRYPTO_PATH_HOST}/peerOrganizations/${ORG2_DOMAIN}/peers/${ORG2_PEER0_ID}/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - \"${ORG2_PEER0_PORT_EXTERNAL}:${ORG2_PEER0_PORT_INTERNAL}\"
    networks:
      - ${COMPOSE_PROJECT_NAME}
