apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.chaincode.name }}-chaincode-svc"
  labels:
    name: "{{ .Values.chaincode.name }}-chaincode-svc"
spec:
  type: NodePort
  ports:
    - name: "port-{{ .Values.chaincode.port }}"
      port: {{ .Values.chaincode.port }}
      protocol: TCP
  selector:
    name: "{{ .Values.chaincode.name }}-chaincode"
