apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
  labels:
    name: "{{ .Release.Name }}-svc"
spec:
  type: NodePort
  ports:
    - name: "port-{{ .Values.chaincode.port }}"
      port: {{ .Values.chaincode.port }}
      protocol: TCP
  selector:
    name: "{{ .Release.Name }}"
