tags:
  ordering: true
  peer: false

orderer:
  org:
    mspId: OrdererOrg
    domain: example.com

  mspPath: "/Users/zemtsov/go/src/github.com/zemtsov/hlf_test/k8s/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp"
  tlsPath: "/Users/zemtsov/go/src/github.com/zemtsov/hlf_test/k8s/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/tls"

  portInternal: 7050
  portExternal: 30050

  portAdminInternal: 7053
  portAdminExternal: 30053
